# Copyright (c) 2020 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.6'

services:
  ## Define Imagestore service which hosts minio dbs
  ia_imagestore:
    depends_on:
      - ia_common
    build:
      context: $PWD/../ImageStore
      dockerfile: $PWD/../ImageStore/Dockerfile
      args:
        EII_VERSION: ${EII_VERSION}
        MINIO_VERSION: ${MINIO_VERSION}
        EII_UID: ${EII_UID}
        EII_USER_NAME: ${EII_USER_NAME}
        UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
        CMAKE_INSTALL_PREFIX: ${EII_INSTALL_PATH}
    read_only : true
    image: ${DOCKER_REGISTRY}openedgeinsights/ia_imagestore:${EII_VERSION}
    container_name: ia_imagestore
    hostname: ia_imagestore
    restart: unless-stopped
    ipc: "none"
    security_opt:
    - no-new-privileges    
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m    
    environment:
      AppName: "ImageStore"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - 5669:5669
    networks:
      - eii
    volumes:
      - "$EII_INSTALL_PATH/data:/data"
      - "vol_eii_socket:${SOCKET_DIR}"
      - "vol_imagestore_conf:/tmp"
      - ./Certificates/ImageStore:/run/secrets/ImageStore
      - ./Certificates/rootca:/run/secrets/rootca

volumes:
  vol_imagestore_conf:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
