# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImageStore.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ImageStore.proto',
  package='ImageStore',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10ImageStore.proto\x12\nImageStore\"\x1e\n\x07ReadReq\x12\x13\n\x0breadKeyname\x18\x01 \x01(\t\"\x19\n\x08ReadResp\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"-\n\x08StoreReq\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\x12\x12\n\nmemoryType\x18\x02 \x01(\t\"!\n\tStoreResp\x12\x14\n\x0cstoreKeyname\x18\x01 \x01(\t\"\x1f\n\tRemoveReq\x12\x12\n\nremKeyname\x18\x01 \x01(\t\"\x0c\n\nRemoveResp2\xb0\x01\n\x02is\x12\x35\n\x04Read\x12\x13.ImageStore.ReadReq\x1a\x14.ImageStore.ReadResp\"\x00\x30\x01\x12\x38\n\x05Store\x12\x14.ImageStore.StoreReq\x1a\x15.ImageStore.StoreResp\"\x00(\x01\x12\x39\n\x06Remove\x12\x15.ImageStore.RemoveReq\x1a\x16.ImageStore.RemoveResp\"\x00\x62\x06proto3')
)




_READREQ = _descriptor.Descriptor(
  name='ReadReq',
  full_name='ImageStore.ReadReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='readKeyname', full_name='ImageStore.ReadReq.readKeyname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=62,
)


_READRESP = _descriptor.Descriptor(
  name='ReadResp',
  full_name='ImageStore.ReadResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk', full_name='ImageStore.ReadResp.chunk', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=89,
)


_STOREREQ = _descriptor.Descriptor(
  name='StoreReq',
  full_name='ImageStore.StoreReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk', full_name='ImageStore.StoreReq.chunk', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memoryType', full_name='ImageStore.StoreReq.memoryType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=136,
)


_STORERESP = _descriptor.Descriptor(
  name='StoreResp',
  full_name='ImageStore.StoreResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='storeKeyname', full_name='ImageStore.StoreResp.storeKeyname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=171,
)


_REMOVEREQ = _descriptor.Descriptor(
  name='RemoveReq',
  full_name='ImageStore.RemoveReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='remKeyname', full_name='ImageStore.RemoveReq.remKeyname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=204,
)


_REMOVERESP = _descriptor.Descriptor(
  name='RemoveResp',
  full_name='ImageStore.RemoveResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=218,
)

DESCRIPTOR.message_types_by_name['ReadReq'] = _READREQ
DESCRIPTOR.message_types_by_name['ReadResp'] = _READRESP
DESCRIPTOR.message_types_by_name['StoreReq'] = _STOREREQ
DESCRIPTOR.message_types_by_name['StoreResp'] = _STORERESP
DESCRIPTOR.message_types_by_name['RemoveReq'] = _REMOVEREQ
DESCRIPTOR.message_types_by_name['RemoveResp'] = _REMOVERESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReadReq = _reflection.GeneratedProtocolMessageType('ReadReq', (_message.Message,), dict(
  DESCRIPTOR = _READREQ,
  __module__ = 'ImageStore_pb2'
  # @@protoc_insertion_point(class_scope:ImageStore.ReadReq)
  ))
_sym_db.RegisterMessage(ReadReq)

ReadResp = _reflection.GeneratedProtocolMessageType('ReadResp', (_message.Message,), dict(
  DESCRIPTOR = _READRESP,
  __module__ = 'ImageStore_pb2'
  # @@protoc_insertion_point(class_scope:ImageStore.ReadResp)
  ))
_sym_db.RegisterMessage(ReadResp)

StoreReq = _reflection.GeneratedProtocolMessageType('StoreReq', (_message.Message,), dict(
  DESCRIPTOR = _STOREREQ,
  __module__ = 'ImageStore_pb2'
  # @@protoc_insertion_point(class_scope:ImageStore.StoreReq)
  ))
_sym_db.RegisterMessage(StoreReq)

StoreResp = _reflection.GeneratedProtocolMessageType('StoreResp', (_message.Message,), dict(
  DESCRIPTOR = _STORERESP,
  __module__ = 'ImageStore_pb2'
  # @@protoc_insertion_point(class_scope:ImageStore.StoreResp)
  ))
_sym_db.RegisterMessage(StoreResp)

RemoveReq = _reflection.GeneratedProtocolMessageType('RemoveReq', (_message.Message,), dict(
  DESCRIPTOR = _REMOVEREQ,
  __module__ = 'ImageStore_pb2'
  # @@protoc_insertion_point(class_scope:ImageStore.RemoveReq)
  ))
_sym_db.RegisterMessage(RemoveReq)

RemoveResp = _reflection.GeneratedProtocolMessageType('RemoveResp', (_message.Message,), dict(
  DESCRIPTOR = _REMOVERESP,
  __module__ = 'ImageStore_pb2'
  # @@protoc_insertion_point(class_scope:ImageStore.RemoveResp)
  ))
_sym_db.RegisterMessage(RemoveResp)



_IS = _descriptor.ServiceDescriptor(
  name='is',
  full_name='ImageStore.is',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=221,
  serialized_end=397,
  methods=[
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='ImageStore.is.Read',
    index=0,
    containing_service=None,
    input_type=_READREQ,
    output_type=_READRESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Store',
    full_name='ImageStore.is.Store',
    index=1,
    containing_service=None,
    input_type=_STOREREQ,
    output_type=_STORERESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Remove',
    full_name='ImageStore.is.Remove',
    index=2,
    containing_service=None,
    input_type=_REMOVEREQ,
    output_type=_REMOVERESP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IS)

DESCRIPTOR.services_by_name['is'] = _IS

# @@protoc_insertion_point(module_scope)
