# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ImageStore_pb2 as ImageStore__pb2


class isStub(object):
  """The ImageStore service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Read = channel.unary_stream(
        '/ImageStore.is/Read',
        request_serializer=ImageStore__pb2.ReadReq.SerializeToString,
        response_deserializer=ImageStore__pb2.ReadResp.FromString,
        )
    self.Store = channel.stream_unary(
        '/ImageStore.is/Store',
        request_serializer=ImageStore__pb2.StoreReq.SerializeToString,
        response_deserializer=ImageStore__pb2.StoreResp.FromString,
        )
    self.Remove = channel.unary_unary(
        '/ImageStore.is/Remove',
        request_serializer=ImageStore__pb2.RemoveReq.SerializeToString,
        response_deserializer=ImageStore__pb2.RemoveResp.FromString,
        )


class isServicer(object):
  """The ImageStore service definition.
  """

  def Read(self, request, context):
    """**********ImageStore Interfaces***************
    Read external interface
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Store(self, request_iterator, context):
    """Store external interface
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Remove(self, request, context):
    """Remove external interface
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_isServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Read': grpc.unary_stream_rpc_method_handler(
          servicer.Read,
          request_deserializer=ImageStore__pb2.ReadReq.FromString,
          response_serializer=ImageStore__pb2.ReadResp.SerializeToString,
      ),
      'Store': grpc.stream_unary_rpc_method_handler(
          servicer.Store,
          request_deserializer=ImageStore__pb2.StoreReq.FromString,
          response_serializer=ImageStore__pb2.StoreResp.SerializeToString,
      ),
      'Remove': grpc.unary_unary_rpc_method_handler(
          servicer.Remove,
          request_deserializer=ImageStore__pb2.RemoveReq.FromString,
          response_serializer=ImageStore__pb2.RemoveResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ImageStore.is', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
